# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cyprienquivet/Documents/GIT/Realisation_Systeme

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cyprienquivet/Documents/GIT/Realisation_Systeme

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cyprienquivet/Documents/GIT/Realisation_Systeme/CMakeFiles /Users/cyprienquivet/Documents/GIT/Realisation_Systeme/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cyprienquivet/Documents/GIT/Realisation_Systeme/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Borne

# Build rule for target.
Borne: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Borne
.PHONY : Borne

# fast build rule for target.
Borne/fast:
	$(MAKE) -f CMakeFiles/Borne.dir/build.make CMakeFiles/Borne.dir/build
.PHONY : Borne/fast

src/borne.o: src/borne.cpp.o

.PHONY : src/borne.o

# target to build an object file
src/borne.cpp.o:
	$(MAKE) -f CMakeFiles/Borne.dir/build.make CMakeFiles/Borne.dir/src/borne.cpp.o
.PHONY : src/borne.cpp.o

src/borne.i: src/borne.cpp.i

.PHONY : src/borne.i

# target to preprocess a source file
src/borne.cpp.i:
	$(MAKE) -f CMakeFiles/Borne.dir/build.make CMakeFiles/Borne.dir/src/borne.cpp.i
.PHONY : src/borne.cpp.i

src/borne.s: src/borne.cpp.s

.PHONY : src/borne.s

# target to generate assembly for a file
src/borne.cpp.s:
	$(MAKE) -f CMakeFiles/Borne.dir/build.make CMakeFiles/Borne.dir/src/borne.cpp.s
.PHONY : src/borne.cpp.s

src/lecteurcarte.o: src/lecteurcarte.cpp.o

.PHONY : src/lecteurcarte.o

# target to build an object file
src/lecteurcarte.cpp.o:
	$(MAKE) -f CMakeFiles/Borne.dir/build.make CMakeFiles/Borne.dir/src/lecteurcarte.cpp.o
.PHONY : src/lecteurcarte.cpp.o

src/lecteurcarte.i: src/lecteurcarte.cpp.i

.PHONY : src/lecteurcarte.i

# target to preprocess a source file
src/lecteurcarte.cpp.i:
	$(MAKE) -f CMakeFiles/Borne.dir/build.make CMakeFiles/Borne.dir/src/lecteurcarte.cpp.i
.PHONY : src/lecteurcarte.cpp.i

src/lecteurcarte.s: src/lecteurcarte.cpp.s

.PHONY : src/lecteurcarte.s

# target to generate assembly for a file
src/lecteurcarte.cpp.s:
	$(MAKE) -f CMakeFiles/Borne.dir/build.make CMakeFiles/Borne.dir/src/lecteurcarte.cpp.s
.PHONY : src/lecteurcarte.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Borne"
	@echo "... src/borne.o"
	@echo "... src/borne.i"
	@echo "... src/borne.s"
	@echo "... src/lecteurcarte.o"
	@echo "... src/lecteurcarte.i"
	@echo "... src/lecteurcarte.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

